from .embeds import EmbeddedSerializers
from .addresses import AddressSerializers
from .appointments import AppointmentSerializers
from .auths import AuthSerializers
from .clinicians import ClinicianSerializers
from .patient_data import PatientDataSerializers
from .patients import PatientSerializers
from .states import StateSerializers
from .users import UserSerializers
